### PR TITLE
Fixes gap between navbar and body

### PR DESCRIPTION
**Pull request by kamikazechaser**
Tested on widescreen (my own pc) and various other sizes!

### CODE REVIEW

**Comment by kamikazechaser** [comment]
image 001 00 08

**Comment by manishrw** [comment]
Hi @kamikazechaser 
It's fine for wide screen device. Could you try it on mobile device (or low resolution device)?
It's getting cropped in my mobile.

image

**Comment by kamikazechaser** [comment]
That is because the page is not responsive from the start!

**Comment by kamikazechaser** [comment]
Closing this because it will conflict with the previous merged PR, I will however open a fresh one that makes it responsive!

**Pull request closed without merging**
